language: node_js
node_js:
    - '4'
addons:
    apt:
        packages:
            - graphviz
dist: trusty
sudo: required
services:
    - docker
before_install: |
    set -ev
    npm install -g npm
    npm config set @ibm:registry https://npm-registry.whitewater.ibm.com
    npm config set //npm-registry.whitewater.ibm.com/:_authToken ${NPM_TOKEN}
install: ./scripts/install-deps.sh
after_success: ./scripts/push-docs.sh
script: |
    set -ev
    ./scripts/run-all-scripts.sh
